ethercat_master:
  time_step:                          0.002
  update_rate_too_low_warn_threshold: 50

ethercat_devices:
  - type:               Elmo
    name:               LeftLegHTAAElmo
    configuration_file: device_configurations/elmo_hip_yaw.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   2

  - type:               Elmo
    name:               LeftLegHAAElmo
    configuration_file: device_configurations/elmo_hip_roll.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   3

  - type:               Elmo
    name:               LeftLegHFEElmo
    configuration_file: device_configurations/elmo_hip_pitch.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   4

  - type:               Elmo
    name:               LeftLegKFEElmo
    configuration_file: device_configurations/elmo_knee.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   5
  
  - type:               Elmo
    name:               LeftLegAAAElmo
    configuration_file: device_configurations/elmo_ankle.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   6

  - type:               Elmo
    name:               LeftLegAFEElmo
    configuration_file: device_configurations/elmo_ankle.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   7

  - type:               Elmo
    name:               RightLegHTAAElmo
    configuration_file: device_configurations/elmo_hip_yaw.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   8

  - type:               Elmo
    name:               RightLegHAAElmo
    configuration_file: device_configurations/elmo_hip_roll.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   9

  - type:               Elmo
    name:               RightLegHFEElmo
    configuration_file: device_configurations/elmo_hip_pitch.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   10

  - type:               Elmo
    name:               RightLegKFEElmo
    configuration_file: device_configurations/elmo_knee.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   11

  - type:               Elmo
    name:               RightLegAAAElmo
    configuration_file: device_configurations/elmo_ankle.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   12

  - type:               Elmo
    name:               RightLegAFEElmo
    configuration_file: device_configurations/elmo_ankle.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   13

  - type:               Elmo
    name:               LeftArmShouderPitchElmo
    configuration_file: device_configurations/elmo_arm_70.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   15

  - type:               Elmo
    name:               LeftArmShouderRollElmo
    configuration_file: device_configurations/elmo_arm_70.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   16

  - type:               Elmo
    name:               LeftArmShouderYawElmo
    configuration_file: device_configurations/elmo_arm_70.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   17

  - type:               Elmo
    name:               LeftArmElbowPitchElmo
    configuration_file: device_configurations/elmo_arm_70.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   18
  
  - type:               Elmo
    name:               LeftArmElbowRollElmo
    configuration_file: device_configurations/elmo_arm_50.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   19

  - type:               Elmo
    name:               LeftArmWristPitchElmo
    configuration_file: device_configurations/elmo_arm_50.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   20

  - type:               Elmo
    name:               LeftArmWristYawElmo
    configuration_file: device_configurations/elmo_arm_50.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   21

  - type:               Elmo
    name:               RightArmShouderPitchElmo
    configuration_file: device_configurations/elmo_arm_70.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   22

  - type:               Elmo
    name:               RightArmShouderRollElmo
    configuration_file: device_configurations/elmo_arm_70.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   23

  - type:               Elmo
    name:               RightArmShouderYawElmo
    configuration_file: device_configurations/elmo_arm_70.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   24

  - type:               Elmo
    name:               RightArmElbowPitchElmo
    configuration_file: device_configurations/elmo_arm_70.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   25
  
  - type:               Elmo
    name:               RightArmElbowRollElmo
    configuration_file: device_configurations/elmo_arm_50.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   26

  - type:               Elmo
    name:               RightArmWristPitchElmo
    configuration_file: device_configurations/elmo_arm_50.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   27

  - type:               Elmo
    name:               RightArmWristYawElmo
    configuration_file: device_configurations/elmo_arm_50.yaml
    ethercat_bus:       enp3s0
    ethercat_address:   28
